[package]
name = "minvect"
version = "0.1.7"
edition = "2021"
license = "MIT"
description = "A mini vector library"
repository = "https://github.com/ThePJB/minvect"

[dependencies]
serde = { version = "1.0.193", features = ["derive"]}